# Generated by Django 3.2.7 on 2021-09-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210916_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_status',
            new_name='paid',
        ),
    ]
