# Generated by Django 3.2.7 on 2021-09-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
