# Generated by Django 3.2.7 on 2021-09-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meroshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
    ]
