# Generated by Django 3.2.7 on 2021-09-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meroshop', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
